### ISSUE TITLE
Can't call service thermiq_mqtt.write_id

### ISSUE THREAD

**Issue by barvidss** [ThermIQ/thermiq_mqtt-ha#18]
## Version of the custom_component
v.1.2.3

## Configuration

```yaml

thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt-bb
  thermiq_dbg: False

```

## Describe the bug
When calling the service thermiq_mqtt.write_id with the provided example values the value is'nt change on the pump and the Core log gives me an error.

How I call the service:
```yaml
service: thermiq_mqtt.write_id
data:
  register_id: sensor.thermiq_rum_bor2
  value: 20
  bitmask: 2
```
## Debug log

```text

ERROR (MainThread) [custom_components.thermiq_mqtt] no value message sent due to faulty reg:[rum_bor2]

```
