### ISSUE TITLE
ThermIQ mqtt messages in explorer but not in HA

### ISSUE THREAD

**Issue by Hoohm** [ThermIQ/thermiq_mqtt-ha#60]
## Version of the custom_component
v2.2.7

## Configuration

```yaml


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

aio_energy_management:
    cheapest_hours:
      - nordpool_entity: sensor.nordpool_kwh_se3_sek_3_10_025
        unique_id: my_cheapest_hours
        name: My Cheapest Hours
        first_hour: 21
        last_hour: 12
        starting_today: true
        number_of_hours: 3
        sequential: false
        failsafe_starting_hour: 1
      - nordpool_entity: sensor.nordpool_kwh_se3_sek_3_10_025
        unique_id: my_expensive_hours
        name: Expensive Hours
        first_hour: 0
        last_hour: 22
        starting_today: false
        number_of_hours: input_number.my_input_number
        sequential: false
        failsafe_starting_hour: 1
        inversed: true

```

## Describe the bug
The thermiq module is installed and seems to be working. All icons are as they should be.

![icons](https://github.com/user-attachments/assets/2bef43e4-4ca7-42ba-aaed-304cdfe13d8e)

Here is what I get in the Mqtt explorer:
```
{"Client_Name":"ThermIQ_4022D8EB1DC8","app_info":"ThermIQ-room2 2.58","reason":"T","rssi":-90,"d0":-2,"d1":21,"d2":1,"d3":20,"d4":0,"d5":36,"d6":31,"d7":53,"d8":0,"d9":2,"d10":-40,"d11":0,"d12":0,"d13":0,"d14":36,"d15":44,"d16":7,"d17":0,"d18":0,"d19":0,"d20":0,"d21":0,"d22":128,"d23":70,"d24":60,"d25":-71,"d26":0,"d27":0,"d28":12,"d29":12,"d30":50,"d31":100,"d32":0,"d33":0,"d34":0,"d35":0,"d36":0,"d37":0,"d38":0,"d39":0,"d40":0,"d41":0,"d42":0,"d43":0,"d44":0,"d45":0,"d46":0,"d47":0,"d48":0,"d49":0,"d50":20,"d51":1,"d52":35,"d53":25,"d54":55,"d55":3,"d56":3,"d57":2,"d58":20,"d59":2,"d60":3,"d61":40,"d62":10,"d63":55,"d64":20,"d65":2,"d66":20,"d67":140,"d68":40,"d69":20,"d70":20,"d71":14,"d72":60,"d73":60,"d74":7,"d75":55,"d76":20,"d77":-15,"d78":18,"d79":60,"d80":15,"d81":2,"d82":20,"d83":60,"d84":60,"d85":0,"d86":0,"d87":0,"d88":0,"d89":0,"d90":0,"d91":0,"d92":0,"d93":0,"d94":0,"d95":0,"d96":0,"d97":0,"d98":69,"d99":1,"d100":3,"d101":3,"d102":0,"d103":1,"d104":52734,"d105":24013,"d106":1373,"d107":65029,"d108":4094,"d109":15,"d110":0,"d111":0,"d112":0,"d113":9728,"d114":806,"d115":3,"d116":0,"d117":0,"d118":0,"d119":0,"d120":0,"d121":0,"d122":0,"d123":0,"d124":0,"d125":2,"d126":2,"d127":2,"INDR_T": 20.5, "EVU":0,"time": "2024-12-23 16:07:47 CET","timestamp": 1734966467 }
```

I deleted the integration, HACS component and all helpers and went through all the installation steps again to make sure it wasn't some weird bug.

There is nothing coming through from mqtt to HA regarding the module. Hence, nothing show up in the custom component: 
<img width="547" alt="image" src="https://github.com/user-attachments/assets/e6a1459d-f0d4-415c-a498-64c48c6381ab" />

I have noticed in other issues that people where showing some configuration entry string that I might be lacking but I can't find the instruction as to what to put in there from the documentation.

Usually, when I use zigbee to mqtt devices, I just add them through zigbee2mqtt. I believe I need somehow to allow the termIQ to send messages to HA.

Thank you for your help :)

## Debug log
No logs sadly
